version: '3.5'

services:
  aspace_checker:
    container_name: 'aspace-checker'
    build:
      context: './'
      dockerfile: 'Dockerfile'
    environment:
      RACK_ENV: 'development'
    volumes:
      - "./logs:/home/archeck/logs"
    ports:
      - '19127:9292'
